version: '3.8'
services:
  ollama-webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - './volumes/ollama:/app/backend/data'
    container_name: 'ollama-webui'
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    networks:
      - common
networks:
  common:
    external: true
