version: '3.8'
services:
  registry:
    restart: unless-stopped
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry-data:/var/lib/registry
      - registry-certs:/certs
      - registry-auth:/auth
    container_name: 'registry'
    networks:
        - cicd
volumes:
  registry-data: null
  registry-certs: null
  registry-auth: null
networks:
  cicd:
    external: true
