version: '3.8'
services:
  postgres-db:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - cicd
    volumes:
      - 'pgsql:/var/lib/postgresql/data/'
volumes:
  pgsql: null

networks:
  cicd:
    external: true
