services:
  hoppscotch:
    image: 'hoppscotch/hoppscotch:2023.12.6'
    restart: unless-stopped
    container_name: 'hoppscotch'
    ports:
      - '172.17.0.1:3000:3000'
      - '172.17.0.1:3100:3100'
      - '172.17.0.1:3170:3170'
    networks:
      - common
    env_file:
      - .env
networks:
  common:
    external: true
