services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./volumes:/home/node/.n8n
    networks:
      - common
networks:
  common:
    external: true
