version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '172.17.0.1:80:80'
      - '172.17.0.1:81:81'
      - '172.17.0.1:443:443'
    volumes:
      - './volumes/nginx-proxy-manager-data:/data'
      - './volumes/nginx-proxy-manager-letsencrypt:/etc/letsencrypt'
    container_name: 'nginx-proxy-manager'
    networks:
      - common
networks:
  common:
    external: true