version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '172.17.0.1:80:80'
      - '172.17.0.1:81:81'
      - '172.17.0.1:443:443'
    volumes:
      - 'nginx-proxy-manager-data:/data'
      - 'nginx-proxy-manager-letsencrypt:/etc/letsencrypt'
    container_name: 'nginx-proxy-manager'
    networks:
      - cicd
volumes:
  nginx-proxy-manager-data: null
  nginx-proxy-manager-letsencrypt: null

networks:
  cicd:
    external: true