services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost'
    volumes:
      - './volumes/gitlab-config:/etc/gitlab'
      - './volumes/gitlab-logs:/var/log/gitlab'
      - './volumes/gitlab-data:/var/opt/gitlab'
    shm_size: '256m'
    container_name: 'gitlab'
    networks:
      - common
networks:
  common:
    external: true
