version: '3.8'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    shm_size: '256m'
    container_name: 'gitlab'
    networks:
      - cicd
volumes:
  gitlab-config: null
  gitlab-logs: null
  gitlab-data: null
networks:
  cicd:
    external: true
