version: '3.8'
services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    networks:
      - cicd
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - cicd
secrets:
  postgresql_password:
    file: odoo_pg_pass
volumes:
  odoo-web-data:
networks:
  cicd:
    external: true