services:
  ollama-webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    restart: unless-stopped
    ports:
      - '172.17.0.1:8080:8080'
    volumes:
      - './volumes/ollama-webui:/app/backend/data'
    container_name: 'ollama-webui'
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    networks:
      - common
networks:
  common:
    external: true
