version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins:/var/jenkins_home
    container_name: 'jenkins'
    networks:
      - cicd
  jenkins-ssh-agent:
    image: jenkins/ssh-agent
    restart: on-failure
    container_name: 'jenkins-ssh-agent'
    networks:
      - cicd
volumes:
  jenkins: null
networks:
  cicd:
    external: true
