services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
    container_name: 'jenkins'
    networks:
      - common
  jenkins-ssh-agent:
    image: jenkins/ssh-agent
    restart: on-failure
    container_name: 'jenkins-ssh-agent'
    networks:
      - common
networks:
  common:
    external: true
