version: '3.8'
services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    restart: unless-stopped
    volumes:
      - './volumes/portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    container_name: 'portainer'
    networks:
      - common
networks:
  common:
    external: true
