version: '3.8'
services:
  mysql-server:
    restart: unless-stopped
    image: 'mysql:8.0.19'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - '172.17.0.1:3306:3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
    networks:
      - common
    container_name: 'mysql'
networks:
  common:
    external: true
