services:
  ollama:
    image: 'ollama/ollama'
    restart: unless-stopped
    ports:
      - '172.17.0.1:11434:11434'
    volumes:
      - './volumes/ollama:/root/.ollama'
    container_name: 'ollama'
    networks:
      - common
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  common:
    external: true