version: '3.8'
services:
  mysql-server:
    restart: always
    image: 'mysql:8.0.19'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - cicd
    container_name: 'mysql'
volumes:
  mysql: null

networks:
  cicd:
    external: true
