version: '3.8'
services:
  app:
    restart: unless-stopped
    image: 'quay.io/minio/minio:latest'
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - './volumes/minio:/data'
    container_name: 'minio'
    networks:
      - common
networks:
  common:
    external: true
