version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    volumes:
      - 'mongodb:/data/db'
    networks:
      - cicd
volumes:
  mongo: null

networks:
  cicd:
    external: true