services:
  postgres-db:
    restart: unless-stopped
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - common
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - './volumes/postgres-data:/var/lib/postgresql/data/'
networks:
  common:
    external: true
