services:
  mc:
    container_name: minecraft-server
    restart: unless-stopped
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
    volumes:
      - './volumes/mc-data:/data'
    networks:
      - common
  proxy1:
    container_name: minecraft-proxy1
    restart: unless-stopped
    image: itzg/mc-proxy
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
    ports:
      - "25560:25577"
    volumes:
      - './volumes/proxy1-data:/server'
    networks:
      - common
  proxy2:
    container_name: minecraft-proxy2
    restart: unless-stopped
    image: itzg/mc-proxy
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
    ports:
      - "25561:25577"
    volumes:
      - './volumes/proxy2-data:/server'
    networks:
      - common
  proxy3:
    container_name: minecraft-proxy3
    restart: unless-stopped
    image: itzg/mc-proxy
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
    ports:
      - "25562:25577"
    volumes:
      - './volumes/proxy3-data:/server'
    networks:
      - common
  lb1:
    container_name: minecraft-loadbalancer
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "25565:25577"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - './volumes/lb1-logs:/var/log/nginx/'
    networks:
      - common
networks:
  common:
    external: true
