services:
  gogs:
    image: 'gogs/gogs:latest'
    restart: on-failure
    volumes:
      - './volumes/gogs:/data/gogs'
    container_name: 'gogs'
    networks:
      - common
networks:
  common:
    external: true
