version: '3.8'
services:
  ollama:
    image: 'ollama/ollama:0.1.32'
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - './volumes/ollama:/root/.ollama'
    container_name: 'ollama'
    networks:
      - common
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
networks:
  common:
    external: true
