services:
  redis-server:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - common
    container_name: "redis"
networks:
  common:
    external: true
